language: objective-c
cache:
  - bundler
  - cocoapods
osx_image: xcode9.2
notifications:
  email:
    - readinglist@andrewbennet.com
before_install:
  - bundle install > /dev/null
  - pod repo update > /dev/null
  - pod install
script:
  - |
    fastlane test
    if [ $TRAVIS_TAG = 'beta' ]; then
    fastlane beta
    fi
