language: swift
cache:
  - bundler
osx_image: xcode10
notifications:
  email:
    - feedback@readinglist.app
before_install:
  - bundle install > /dev/null
  - brew install mint
  - mint run yonaskolb/xcodegen --verbose
  - pod repo update > /dev/null
  - pod install
script:
  - set -e
  - if [[ ! $TRAVIS_COMMIT_MESSAGE =~ '[SKIP-TESTS]' ]]; then bundle exec fastlane test; fi
  - if [[ $TRAVIS_COMMIT_MESSAGE =~ '[DEPLOY]' ]]; then bundle exec fastlane deploy; fi
