language: objective-c
cache:
  - bundler
osx_image: xcode9.3beta
notifications:
  email:
    - readinglist@andrewbennet.com
before_install:
  - bundle install > /dev/null
  - pod repo update > /dev/null
  - pod install
script:
  - set -e
  - if [[ ! $TRAVIS_COMMIT_MESSAGE =~ '[SKIP-TESTS]' ]]; then fastlane test; fi
  - if [[ $TRAVIS_COMMIT_MESSAGE =~ '[DEPLOY]' ]]; then fastlane deploy; fi
