language: swift
cache:
  - bundler
osx_image: xcode10
notifications:
  email:
    - feedback@readinglist.app
before_install: # xcodegen project file generation removed until https://github.com/yonaskolb/XcodeGen/issues/391 is fixed
  - bundle install > /dev/null
  - pod repo update > /dev/null
  - pod install
script:
  - set -e
  - if [[ ! $TRAVIS_COMMIT_MESSAGE =~ '[SKIP-TESTS]' ]]; then bundle exec fastlane test; fi
  - if [[ $TRAVIS_COMMIT_MESSAGE =~ '[DEPLOY]' ]]; then bundle exec fastlane deploy; fi
