language: objective-c
osx_image: xcode9.2
before_install:
  - pod repo update > /dev/null
xcode_workspace: ReadingList.xcworkspace
xcode_scheme: ReadingList
script:
  - xcodebuild test -workspace ReadingList.xcworkspace -scheme ReadingList -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' CODE_SIGNING_REQUIRED=NO  | xcpretty && exit ${PIPESTATUS[0]}
  - xcodebuild test -workspace ReadingList.xcworkspace -scheme ReadingList -destination 'platform=iOS Simulator,name=iPhone 7 Plus,OS=10.3.1' CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}
  - xcodebuild test -workspace ReadingList.xcworkspace -scheme ReadingList -destination 'platform=iOS Simulator,name=iPad Pro (9.7-inch),OS=10.3.1' CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}
  - xcodebuild test -workspace ReadingList.xcworkspace -scheme ReadingList -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2' CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}
  - xcodebuild test -workspace ReadingList.xcworkspace -scheme ReadingList -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=11.2' CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}
  - xcodebuild test -workspace ReadingList.xcworkspace -scheme ReadingList -destination 'platform=iOS Simulator,name=iPad Pro (9.7-inch),OS=11.2' CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}
