language: objective-c
cache:
  - bundler
  - cocoapods
osx_image: xcode9.2
notifications:
  email:
    - readinglist@andrewbennet.com
before_install:
  - bundle install > /dev/null
  - pod repo update > /dev/null
script:
  - fastlane test
deploy:
  provider: script
  script:
    - fastlane beta
  on:
    branch: fastlane
