language: objective-c
osx_image: xcode8.3
before_install:
  - pod repo update > /dev/null
xcode_workspace: books.xcworkspace
xcode_scheme: books
script:
  - xcodebuild test -workspace books.xcworkspace -scheme books -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' CODE_SIGNING_REQUIRED=NO
