language: swift
cache:
  - bundler
osx_image: xcode10.1
notifications:
  email:
    - feedback@readinglist.app
before_install:
  - ./build/before_install.sh
script:
  - set -e
  - if [[ ! $TRAVIS_COMMIT_MESSAGE =~ '[SKIP-TESTS]' ]]; then bundle exec fastlane test; fi
  - if [[ $TRAVIS_COMMIT_MESSAGE =~ '[DEPLOY]' ]]; then bundle exec fastlane deploy; fi
