language: objective-c
osx_image: xcode9.2
before_install:
  - pod repo update > /dev/null
xcode_workspace: books.xcworkspace
xcode_scheme: books
script:
  - xcodebuild test -workspace books.xcworkspace -scheme books -destination 'platform=iOS Simulator,name=iPhone 8,OS=10.3.1' CODE_SIGNING_REQUIRED=NO
  - xcodebuild test -workspace books.xcworkspace -scheme books -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=10.3.1' CODE_SIGNING_REQUIRED=NO
  - xcodebuild test -workspace books.xcworkspace -scheme books -destination 'platform=iOS Simulator,name=iPad Pro (9.7-inch),OS=10.3.1' CODE_SIGNING_REQUIRED=NO
  - xcodebuild test -workspace books.xcworkspace -scheme books -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2' CODE_SIGNING_REQUIRED=NO
  - xcodebuild test -workspace books.xcworkspace -scheme books -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=11.2' CODE_SIGNING_REQUIRED=NO
  - xcodebuild test -workspace books.xcworkspace -scheme books -destination 'platform=iOS Simulator,name=iPad Pro (9.7-inch),OS=11.2' CODE_SIGNING_REQUIRED=NO
